### ISSUE TITLE
feat(ecc-utils-design): design token utilization

### ISSUE THREAD

**Issue by git-anurag-hub** [elixir-cloud-aai/cloud-components#101]
## Description

Currently, we need to implement a token registration strategy for our application. Tokens will be passed by the user in the form of JSON as a prop. The goal is to register and utilize these tokens effectively within the components. Several use cases must be considered for the implementation:

- Tokens will be used based on the nearest parent wrapper component prop value.
- The package-author can pass a custom id/name to the utility component and expect the user to pass the token based on that name.

## Possible solution(s)

Although a specific solution is not determined yet, there are some points to take into consideration:

- Avoid creating custom design tokens during runtime and utilize predefined tokens and their values in the CSS variables as well.
- Register the token for the root of the wrapper and overwrite in case of a child wrapper.

## Additional context

Updated issue: https://github.com/elixir-cloud-aai/cloud-components/issues/101#issuecomment-1678168256

**Comment by git-anurag-hub** [comment]
Hey @SalihuDickson, I think you had something in mind for this. Maybe you can take this up?

**Comment by git-anurag-hub** [comment]
This current setup could use some performance enhancements and streamlining. A few key observations:

#### Present Setup
The registration logic for now is concentrated within the `ecc-utils-design-wrapper` component. This component taps into the FAST design tokens to lodge CSS values at the root level. 
The code snippet below showcases how this works to customize the look of Button 1 to `text-color` `blue` & `background-color` `pink`:
```
<ecc-utils-design-wrapper
  config='{
    "text-color": "blue",
    "background-color": "pink"
  }'
>
  <ecc-utils-design-button>
    Button 1
  </ecc-utils-design-button>
</ecc-utils-design-wrapper>
```

Moreover, extending this behavior involves including the `name` attribute in the `ecc-utils-design-button` element. This attribute offers a unique identifier and facilitates the transmission of bespoke tokens from the wrapper. The HTML layout would shift as follows:
```
<ecc-utils-design-wrapper
  debug
  config='{
    "text-color": "blue",
    "background-color": "pink",
    "primary": {
      "text-color": "red", 
      "background-color": "pink"
    },
    "secondary": {
      "text-color": "yellow", 
      "background-color": "red"
    }
  }'
>
  <div>
    <ecc-utils-design-button name="primary">
      Button 1.1
    </ecc-utils-design-button>
  </div>
  <ecc-utils-design-button name="secondary">
    Button 1.2
  </ecc-utils-design-button>
  <ecc-utils-design-button>
    Button 1.3
  </ecc-utils-design-button>
</ecc-utils-design-wrapper>
```

In this scenario, Button 1.1 leverages the `name` attribute "primary" to access specific token values, resulting in a `text-color` of `red` and a `background-color` of `pink`. A similar approach applies to Button 1.2, while Button 1.3 maintains default values since it lacks a name attribute.

The current implementation involves the wrapper registering predefined tokens at its root, utilizing the FAST token system. Critically, child components within the wrapper inherit these default token values. This inheritance mechanism, managed internally by FAST, functions smoothly when exclusively dealing with default values. The time complexity of this operation stands at `O(number of default tokens in the config)`.

However, for custom `name` attributes, the current approach iterates through the config keys (e.g., "primary" and "secondary"), seeks matching child components with corresponding names deep within the DOM tree, and enrolls individual tokens for each. The time complexity of this operation rises to `O(number of custom names * number of child DOM elements * number of tokens)`, which can become significant with numerous child DOM elements. This process recurs for every wrapper instance, exacerbating performance concerns.

#### Potential Solutions
- Restrict Custom Names: By limiting the scope of acceptable custom names, performance improvements could be realized. However, this may curtail the flexibility and versatility of the approach.
- Inefficient Space Utilization: The method initially proposed by @SalihuDickson might mitigate performance issues by crafting tokens for each name and token combination. This would generate tokens on-the-fly for each root, instead of initializing a few tokens and then enrolling them with distinct values for each root. Further clarification from @SalihuDickson about the time complexity of this approach could provide insight into its viability.
- Event-Driven Communication: An alternative solution entails emitting an event from the wrapper to all child components. Child components with custom names could then listen for this event and utilize the transmitted information to adjust their behavior.
- Config-Dependent Token Retrieval: Rather than the wrapper registering tokens for child components, child components could directly access token values from the config. This would obviate the need for the wrapper to oversee token registration.

**Comment by JaeAeich** [comment]
As an end user, I find this approach to be a little cumbersome; this is more like writing CSS in style tags and naming the specified element `primary` and `secondary.`

 With this approach, whats the difference between:
```html
<ecc-utils-design-wrapper
  debug
  config='{
    "text-color": "blue",
    "background-color": "pink",
    "primary": {
      "text-color": "red", 
      "background-color": "pink"
    },
    "secondary": {
      "text-color": "yellow", 
      "background-color": "red"
    }
  }'
>
  <div>
    <ecc-utils-design-button name="primary">
      Button 1.1
    </ecc-utils-design-button>
  </div>
  <ecc-utils-design-button name="secondary">
    Button 1.2
  </ecc-utils-design-button>
  <ecc-utils-design-button>
    Button 1.3
  </ecc-utils-design-button>
</ecc-utils-design-wrapper>
```
And the trivial way?

```html
   <style>
   /* Base styles */
   .ecc-utils-design-wrapper {
    color: blue;
    background-color: pink;
   }

  /* Primary button styles */
  .ecc-utils-design-button[class="primary"] {
    color: red;
    background-color: pink;
  }

   /* Secondary button styles */
  .ecc-utils-design-button[class="secondary"] {
    color: yellow;
    background-color: red;
   }
   </style>
    <ecc-utils-design-button class="primary">
      Button 1.1
    </ecc-utils-design-button>
  <ecc-utils-design-button class="secondary">
    Button 1.2
  </ecc-utils-design-button>
  <ecc-utils-design-button class="default">
    Button 1.3
  </ecc-utils-design-button>
```

Also, let's say I have ten buttons on the page with different shadows. Would I have to write ten different names for each?

Sorry, I haven't yet worked with this implementation just played a little, but I can't quite see a whole lot of difference here from [emotion](https://emotion.sh/docs/introduction) or [styled-components](https://styled-components.com), maybe I'm wrong and am overlooking something?

**Comment by git-anurag-hub** [comment]
Yeah @JaeAeich, your solution works perfectly fine when the people defining the `name` property will be in charge of defining the styles too. But in our case, it can conflict. 
Suppose we have 2 package authors both using a button & both giving the `name` `primary` to it & have used them in different contexts & the app author might want to change them differently. So now there are 2 buttons in the DOM with the same `name` (which the app author can't change) & want to customize differently. Something like this:

```
<ecc-utils-design-wrapper
  config='{
    "primary": {
      "text-color": "red", 
      "background-color": "pink"
    }
  }'
>
  <ecc-utils-design-button name="primary">
      Button 1.1
  </ecc-utils-design-button>
</ecc-utils-design-wrapper>
<ecc-utils-design-wrapper
  config='{
    "primary": {
      "text-color": "green", 
      "background-color": "yellow"
    }
  }'
>
  <ecc-utils-design-button name="secondary">
    Button 1.2
  </ecc-utils-design-button>
</ecc-utils-design-wrapper>
```
Here of course we can do that by the CSS property but then we will have to pass the style to `ecc-utils-design-wrapper` by classname (not inline because that is what we are doing right now). Will have to think about its efficiency though if it can be better than the one right now! 
Also, Did I understand you correctly here?

**Comment by SalihuDickson** [comment]
@git-anurag-hub, Concerning the second implementation, I believe it will be more inefficient than what we currently have. It has a time complexity similar to this but slightly worse as the tokens also must be registered on each iteration for the named configs. And while it might start out with a lower space complexity it will very likely overtake the current implementation with even a slightly robust config object. All that to say I think we can discard that implementation.

**Comment by git-anurag-hub** [comment]
Hey @SalihuDickson & @JaeAeich, can you guys look at pr #116 that is the solution I think Javed is talking about but is using the [CSS `::part`](https://developer.mozilla.org/en-US/docs/Web/CSS/::part) property which I belive is better choice due to shadow DOM restriction on the styles & it is working perfectly fine (actually better).

Advantages:
- Meets all of our requirements.
- The user can now pass any of the hundreds of CSS properties to the component not only one we define the token for.
- Time complexity decreases to O(1) (excluding browser CSS handling time).
- We no longer need to manage tokens and related configurations for token naming to a large extent.
- There is no reliance on the FAST design token API, which is gradually becoming outdated.

Cons: 
- Only one major downside, the `package-authors` will now have to use [`exportparts`](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/exportparts) while using design components. 

In my opinion, this approach is significantly better. What do you all think? The cons are minimal compared to the benefits. I would appreciate hearing your thoughts on this matter.

**Comment by git-anurag-hub** [comment]
Also what are your thoughts here @uniqueg, this will change the way the styles are passed to the component by the end user as discussed earlier. I believe though this is the better way to pass the styles as we don't have to manage them they are basically now all the CSS properties you can think of. This is also more efficient & we will have to manage less.

**Comment by uniqueg** [comment]
This discussion is beyond me, so I guess I trust your judgement, @git-anurag-hub, @SalihuDickson and @JaeAeich. But would perhaps be nice to discuss/demo this at an upcoming meeting. Perhaps then I might have something to say as well :)
