### ISSUE TITLE
feat(ecc-utils-design): input field

### ISSUE THREAD

**Issue by git-anurag-hub** [elixir-cloud-aai/cloud-components#115]
## Description

This issue aims to introduce a well-defined and consistent input field component to the ECC Utils design system.

**Comment by SalihuDickson** [comment]
@git-anurag-hub, I've been a little busy over this past week and next week will also be a little bit hectic for me, and there's also the issue of the config issue that I've been trying to work around, but I was hoping to finish setting up testing for the current components before we add more at least so we can be somewhat up-to-date on a testing template while we proceed.

However, if you feel this is urgent you can go ahead and I'll catch up with the testing, so I don't hold you up to much.
