### ISSUE TITLE
feat: css variables

### ISSUE THREAD

**Issue by anuragxxd** [elixir-cloud-aai/cloud-components#159]
## Description

While the design package right now provides the solution for the CSS parts. In some simple use cases, like changing the theme color will be tiresome for the end user using the CSS pasts solution. It will be better for users to have a much easier solution for such small use cases.

## Possible solution(s)

 CSS variables can be used to solve this. There are many implementations using the CSS variables but the general idea will be to have a clear, concise & consistent variables across all components.

**Comment by SalihuDickson** [comment]
Just to get a bit more context on this,  we want to set out properties with css variables to make them easier to alter right? for example to switch btw a light and dark theme like [this](https://shoelace.style/getting-started/themes#activating-themes) but perhaps activated with a property. And then even modifying the values in those themes with just plain css like [this](https://github.com/shoelace-style/shoelace/tree/next/src/themes)

**Comment by psankhe28** [comment]
I'm eager to take on this task. Could y'll please provide additional information on the next steps in proceeding with it?

**Comment by uniqueg** [comment]
@git-anurag-hub @SalihuDickson @JaeAeich Is there an implementation plan for this that you may have discussed since the issue was opened in November? Something that could help @psankhe28 to work on this?

**Comment by JaeAeich** [comment]
We will require discussion on how to name and configure CSS variable as this will be a global thing, and right now CSS parts for some of comp of design package is yet to be considered. @psankhe28 though this would require discussion but if you really wanna work on this maybe checkout how shoelace CSS variable and we can start to write our own or maybe inherit from it.

**Comment by SalihuDickson** [comment]
@psankhe28, like @JaeAeich said, you can take a look at how shoelace implements this feature, you can then contribute by discussing your proposed solution here.

**Comment by JaeAeich** [comment]
@anuragxxd @SalihuDickson This way seems very intuitive, it would be very cool and easy if our CSS variable could be use something like [this](https://ui.shadcn.com/themes). Granted this will require us to revisit alot of design component's CSS, but once done the butterfly effect would make all the component extremenly easy to customise, note how shadcn provides some dafault color palet to play with. We can have such a color picker as well.

Lets discuss the CSS variable in this regards and probably open some issues, maybe experimenting with one design component should give us a good start.
