### ISSUE TITLE
feat: services list

### ISSUE THREAD

**Issue by anuragxxd** [elixir-cloud-aai/cloud-components#166]
This issue create the component as proposed here: https://github.com/elixir-cloud-aai/cloud-components/issues/114#issuecomment-1798438510

**Comment by JaeAeich** [comment]
Yeah @git-anurag-hub this looks right. But for TES atleast rn, you can try this [swagger](protes.rahtiapp.fi/ga4gh/tes/v1/ui/) for more examples.
