### ISSUE TITLE
feat: responsive submit button  

### ISSUE THREAD

**Issue by JaeAeich** [elixir-cloud-aai/cloud-components#175]
## Description
 It would be good to highlight the "Submit" button (bold font, colored background) and gray it out until all required values have been added.

**Comment by SalihuDickson** [comment]
Implementing this in the form package it self might take too much control away from the component authors, I think it would be better if we expose the API of the form a bit more to allow the component authors to implement such a feature on their own. @git-anurag-hub what do you think?

**Comment by SalihuDickson** [comment]
Implementing this in the form package it self might take too much control away from the component authors, I think it would be better if we expose the API of the form a bit more to allow the component authors to implement such a feature on their own. @git-anurag-hub what do you think?

**Comment by SalihuDickson** [comment]
Implementing this in the form package it self might take too much control away from the component authors, I think it would be better if we expose the API of the form a bit more to allow the component authors to implement such a feature on their own. @git-anurag-hub what do you think?

**Comment by psankhe28** [comment]
Can I work on this issue if there isn't anyone currently assigned to it?

**Comment by uniqueg** [comment]
Not sure what the status of this issue is. @JaeAeich @git-anurag-hub @SalihuDickson?

**Comment by JaeAeich** [comment]
@psankhe28 sure go ahead.

**Comment by psankhe28** [comment]
I tried experimenting with changing the button color in the form.md file, but it didn't work. Upon inspecting the styles in the screenshot, I noticed that the changes are applied to ecc-utils-design-form::part(submit-button). However, I am having difficulty locating this in the code.

![image](https://github.com/elixir-cloud-aai/cloud-components/assets/84843461/d5411238-f374-4702-8272-2b9c087257d7)

**Comment by uniqueg** [comment]
It may be best to discuss this on Slack

**Comment by psankhe28** [comment]
Sure.

**Comment by JaeAeich** [comment]
@SalihuDickson if this is fixed please close it :)

**Comment by psankhe28** [comment]
Yes, it is fixed!
