### ISSUE TITLE
triage: required mark (*) on array inputs missing

### ISSUE THREAD

**Issue by JaeAeich** [elixir-cloud-aai/cloud-components#176]
## Description
The asterisk (*) is not visible for inputs in the form component of array type with children.

**Comment by SalihuDickson** [comment]
@JaeAeich  The asterisk implies that the field is required. The array is not an input type and cannot be required, only its children can be. Is there an underlying issue that might be caused by this?

**Comment by JaeAeich** [comment]
@SalihuDickson yeah but it is more intuitive as some forms have array field that is required. Having an asterisk (*) near it . Check out  @uniqueg's suggestions in [here](https://github.com/elixir-cloud-aai/cloud-components/pull/156#issuecomment-1807267330).

**Comment by uniqueg** [comment]
Yes, in that example, at least _one_ executor and at least _one_ command are required (see specs for [`tesTask`](https://github.com/ga4gh/task-execution-schemas/blob/1df37d34242f74d3f03475c6b9de3324b8094054/openapi/task_execution_service.openapi.yaml#L731-L836) and [`tesExecutor`](https://github.com/ga4gh/task-execution-schemas/blob/1df37d34242f74d3f03475c6b9de3324b8094054/openapi/task_execution_service.openapi.yaml#L290-L389)), so I do think it makes sense (and is more intuitive) to put asterisks on the "Executors" object and "Commands" array, respectively, in those cases:

![image](https://github.com/elixir-cloud-aai/cloud-components/assets/10855418/2c6bc39b-338b-4a52-b6ad-b7976d781905).

However, there are also scenarios where an object is _not_ required, but once there _is_ at least one item included, it will require individual properties. In those cases, I think there should be no asterisk on the outer object.
