### ISSUE TITLE
fix: CI cache

### ISSUE THREAD

**Issue by git-anurag-hub** [elixir-cloud-aai/cloud-components#182]
## Description

Cache the NPM dependencies to reduce the CI run minutes!

**Comment by aye-nyeinSan** [comment]
Greeting @git-anurag-hub ! I am exploring projects for GSOC 2024, and I found this ticket interesting for me. I found three workflows in Github actions.  Could you please give me more details to work on ? Thank you.

**Comment by uniqueg** [comment]
Sawatdee khrab and welcome @aye-nyeinSan! And apologies for the late reply - things are a little busy right now.

Please check our [GSoC project ideas](https://summerofcode.withgoogle.com/programs/2024/organizations/global-alliance-for-genomics-and-health), join our [Slack](https://join.slack.com/t/elixir-cloud/shared_invite/zt-1uvebyx1e-NcC0Hof2guT9df~haBdQaw) on channels `#oss-community`, `#gsoc` and `#web-components` and talk to us there (Anurag Gupta or Alex Kanitz, that's me) - you will have a much better response time ;-)

**Comment by piyushs131** [comment]
Hey @aye-nyeinSan,
kindly check the package-lock.json and package.json file. may be this file stops running the exact version of dependencies installed, and preventing changes between CI runs

**Comment by git-anurag-hub** [comment]
> Greeting @git-anurag-hub ! I am exploring projects to contribute in GSOC 2024, and I found this ticket interesting for me. I found three workflows in Github actions. Could you please give me more details to work on ? Thank you.

Hello @aye-nyeinSan, thank you for your interest! We've noticed that our mono repo is causing lengthy installation times whenever the CI/CD process runs. To mitigate this, we're exploring caching options within GitHub Actions, as outlined here: https://github.com/actions/setup-node#caching-global-packages-data.

Considering our use of the Turbo repo, we're also investigating whether leveraging the Turbo cache alongside GitHub Actions cache could provide a more efficient solution. You can delve into this further here: https://turbo.build/repo/docs/ci/github-actions#caching-with-github-actionscache.

Could you assist in identifying the optimal caching solution for our setup? Additionally, this presents an opportunity to delve deeper into managing the Turbo cache effectively. More information on this can be found here: https://turbo.build/repo/docs/core-concepts/caching.

Please don't hesitate to reach out with any questions or clarifications!

**Comment by JaeAeich** [comment]
@git-anurag-hub I thought this was a regular caching issue please checkout #237, @aye-nyeinSan please feel free to layer this PR with turbo-repo optimisation as well :) or maybe create another.
