### ISSUE TITLE
triage: remove vitepress

### ISSUE THREAD

**Issue by anuragxxd** [elixir-cloud-aai/cloud-components#188]
## Description

It will be better to ditch Vitepress. Why? As it uses vue under the hood. For our use case, it will be better to have something like Nextra which uses next.js. It will I guess be more manageable & will align with out goals as we will be building the components for the react. 

## Possible solution(s)

Nextra: https://nextra.site/

**Comment by SalihuDickson** [comment]
Sure, @git-anurag-hub. I'll start working on the script for the react build.

**Comment by JaeAeich** [comment]
@git-anurag-hub Have you tried anything on `nextra`, should I try it as well?
