### ISSUE TITLE
Error: Cannot find module 'esbuild'

### ISSUE THREAD

**Issue by EslamAsHhraf** [elixir-cloud-aai/cloud-components#226]
## Description

After Run  ```npm run dev``` I got Error: Cannot find module 'esbuild'

![image](https://github.com/elixir-cloud-aai/cloud-components/assets/71986226/b9a84931-1766-437a-89a1-f3d05ae88c0e)

**Comment by uniqueg** [comment]
Thanks for reporting, @EslamAsHhraf. @git-anurag-hub, @JaeAeich, @SalihuDickson: can you pls check what's going on here? :pray:

**Comment by EslamAsHhraf** [comment]
@JaeAeich Thanks, I don't run on the root.♥️♥️
