### ISSUE TITLE
chore: remove dist when running build 

### ISSUE THREAD

**Issue by JaeAeich** [elixir-cloud-aai/cloud-components#246]
## Description

Automatically remove `dist/` when building a package.

## Possible solution(s)

use [rimraf](https://www.npmjs.com/package/rimraf) to delete dist folder before trying to build the package.

_Packages: @elixir-cloud/lit-tes, @elixir-cloud/lit-wes, @elixir-cloud/design_

**Comment by SalihuDickson** [comment]
@JaeAeich  The build scripts already handle this. It removes the `dist` dir and creates a new one on every build.

**Comment by JaeAeich** [comment]
my bad, missed this. Closing this issue as `scripts/build.js` handles this as
```js
...
nextTask("Cleaning up previous build", () => {
  bundleDirectories.map((dir) =>
    fs.rmSync(dir, { force: true, recursive: true })
  );

  bundleDirectories.map((dir) =>
    fs.mkdirSync(dir, {
      recursive: true,
    })
  );
});
...
```
