### ISSUE TITLE
chore: remove storybook 

### ISSUE THREAD

**Issue by JaeAeich** [elixir-cloud-aai/cloud-components#250]
## Description

Cleanup all the packages, and remove storybook from them. We are using docs to document out component yet some packages have storybook as a dependency.

**Comment by valens200** [comment]
Thank you @JaeAeich , do you mean to remove those story since we are no longer depending on them?

**Comment by psankhe28** [comment]
@JaeAeich , does this also include clearing the package-lock.json?
