### ISSUE TITLE
chore: type hints 

### ISSUE THREAD

**Issue by JaeAeich** [elixir-cloud-aai/cloud-components#251]
## Description

With #229 being merged, `types` of components are being exported, use these types and reduce number fo eslint warning that it throws.
## Possible solution(s)

Import the types from `/package/component_name/types.d.ts` and use then in place where `any` is being used.

**Comment by psankhe28** [comment]
@anantJjain, are you still working on this or may I proceed with it?

**Comment by JaeAeich** [comment]
My bad guys I have been working on this! I forgot to link the issue.
