### ISSUE TITLE
feat: add API to fields configs 

### ISSUE THREAD

**Issue by JaeAeich** [elixir-cloud-aai/cloud-components#253]
## Description
In the current behaviour, when the fields is passed it replaces the previous set configuration of fields (structural design of runs components). Since there will be multiple implementation of WES and TES which might not be compliant, it might be a good idea to give the feature of extending default config rather than always replacing it.

## Possible solution(s)

Add `extends` API(prop) to `ecc-client-litga4gh-tes-runs` and `ecc-client-lit-ga4gh-wes-runs`, and now when the `app-author` passes `extends=true` the `fields` passes should extend the default fields/config.

**Comment by uniqueg** [comment]
If I understand this correctly, this makes sense even for compliant implementations, because the GA4GH API specs generally do not prohibit additional properties in their models.
