### ISSUE TITLE
fix: remove `React` generated code and rename generated `React` dirs 

### ISSUE THREAD

**Issue by JaeAeich** [elixir-cloud-aai/cloud-components#268]
## Description

The name generated for `React` build in `src` folder is different for wes and tes package. 
![image](https://github.com/elixir-cloud-aai/cloud-components/assets/100477031/08e1ab73-4a04-4509-b1f1-cd313b501aec)

> IMO, the ideal behaviour would be that dir name be the same as that of dir name that contains to code not the name of the component for it to be cconsistent.

`build` script generates `react` directories inside `src`, we need to clean up this on every `build` run otherwise it conflicts with subsequent builds.

**Comment by JaeAeich** [comment]
@SalihuDickson Please look into cleanup as well.

**Comment by SalihuDickson** [comment]
@JaeAeich, if you mean deleting the react dir before every build, that is already being done.

**Comment by JaeAeich** [comment]
@SalihuDickson no that is not being done. But seems like @git-anurag-hub is working on it in #281

**Comment by SalihuDickson** [comment]
@JaeAeich, yes it is. But it seems the ts compiler is being run before that. That's probably what is causing issues. I'll take a look at why that is happening.

**Comment by SalihuDickson** [comment]
I guess we can also add to this, for the sake of tracking; Add clean up functions to the build process in the case of failure or user interruption  during the build process.
