### ISSUE TITLE
triage: LICENCE

### ISSUE THREAD

**Issue by JaeAeich** [elixir-cloud-aai/cloud-components#269]
## Description

Currently mentioned in the docs, that "this project is release under MIT licence", but all the monorepo has `apache` and packages have `MIT` licence. Since we are migrating to [nextra](https://github.com/elixir-cloud-aai/cloud-components/pull/262), should I change LICENCE desc to `apache`.

**Comment by JaeAeich** [comment]
@uniqueg Whats the call here, do we change the [LICENCE of monorepo](https://github.com/elixir-cloud-aai/cloud-components/blob/main/LICENSE) or should I just update the licence info in the docs?

**Comment by uniqueg** [comment]
Please update the license in the docs to match the license file in the repo. We use Apache 2.0 in all of the backend services, so probably makes sense to use it for the frontend stuff as well.

**Comment by JaeAeich** [comment]
@git-anurag-hub you are working on removing fast packages, please can you change the License int the packages as well, and in the handlebar files.
