### ISSUE TITLE
fix: Empty CONTRIBUTING.md file 

### ISSUE THREAD

**Issue by iceddrop** [elixir-cloud-aai/cloud-components#283]
## Description

The contribution guidelines is missing from the documentation file.

## Possible solution(s)

I have written the contribution guidelines that I got from [here](https://demo.hedgedoc.org/JxJWZ9eNRpKdZkU-u6Sx1g#point-6) into the empty CONTRIBUTING.md file in markdown format.
![image_2024-03-25_232112738](https://github.com/elixir-cloud-aai/cloud-components/assets/93996532/627f6418-e978-426f-9907-5700cb84467d)

**Comment by iceddrop** [comment]
Pls assign this issue to me , thanks

**Comment by JaeAeich** [comment]
To be fixed in #262
