### ISSUE TITLE
chore: remove all contributors

### ISSUE THREAD

**Issue by anuragxxd** [elixir-cloud-aai/cloud-components#286]
## Description

This issue removes all contributors from the repo. Currently, this feature is not actively utilized, and maintaining it adds unnecessary overhead. The list of contributors is already provided by GitHub in repo itself.

**Comment by psankhe28** [comment]
Hi @anuragxxd , Can you please provide more details regarding this?

**Comment by anuragxxd** [comment]
Thank you @psankhe28 for your interest. This issue is currently in the triage stage and hasn't been confirmed for development yet.

@uniqueg  might have more insights on this since he set up the all-contributors system. While I don't believe keeping all-contributors is strictly required, I understand the rationale behind it – in that case this issue could potentially involve fixing aspects related to all contributors.

**Comment by uniqueg** [comment]
Thanks @anuragxxd! I very much like the idea of [All Contributors](https://allcontributors.org/), which is much more inclusive and fine-grained compared to the list that is automatically maintained by GitHub. However, I also acknowledge that it's not sustainable as long as we don't automate its use (e.g., via bots that recognize participation through posting of issues, PRs, discussions etc).

So yes, a bit sad to see it go, but given that it's not a priority right now to work out its automation, it's probably best to remove it - at least for now.

**Comment by uniqueg** [comment]
Not quite sure how to remove it. Maybe removing the `ALL-CONTRIBUTORS-LIST` from [this file](https://raw.githubusercontent.com/elixir-cloud-aai/cloud-components/main/CONTRIBUTORS.md) is all it takes?

**Comment by anuragxxd** [comment]
> Not quite sure how to remove it. Maybe removing the `ALL-CONTRIBUTORS-LIST` from [this file](https://raw.githubusercontent.com/elixir-cloud-aai/cloud-components/main/CONTRIBUTORS.md) is all it takes?

I guess so some more places I found:
- Turn off the all contributors bot on github too. @uniqueg maybe you can turn that off here https://github.com/elixir-cloud-aai/cloud-components/settings/installations. 
- This file too [here](https://github.com/elixir-cloud-aai/cloud-components/settings/installations).

@psankhe28 if you want you can remove these files & revalidate if there are any other places all-contributors exist & make a PR.

**Comment by psankhe28** [comment]
Sure, I will work on it.
