### ISSUE TITLE
ci: enforce semantic pull requests

### ISSUE THREAD

**Issue by git-anurag-hub** [elixir-cloud-aai/cloud-components#33]
**Please describe your issue.**

**EDIT BY @uniqueg: ENFORCE SEMANTIC PULL REQUESTS, SEE END OF DISCUSSION BELOW.**

The initial implementation of enforcing a commit message template using the conventional commit format and pre-commit hook script has been completed successfully in #29. However, there are several remaining tasks to finalize the implementation and enhance the versioning and release changelog process. The following tasks need to be completed:

**Additional context**
These remaining tasks will further improve the tracking, visibility, and consistency of the components developers are working on within our codebase.

- [ ] Limit commit title size to 50: Currently, there is default restriction on the length of commit titles. To adhere to the defined requirements, we need to implement a validation mechanism that limits the commit title size to 50 characters.
- [ ] ~Write auto comments for commit: To improve the visibility and traceability of commits, it would be beneficial to automatically generate comments for each commit. These comments can include relevant information such as the commit message, associated Jira or issue numbers, and any other necessary details.~ **CREATE SEPARATE ISSUE**
- [ ] ~Pre-commit lint and test scripts: Implement pre-commit linting and testing scripts that run automatically before each commit. These scripts will help ensure that the code changes made by developers adhere to the project's coding standards and pass all relevant tests.~ #35 
- [ ] ~Versioning and release changelog enhancement: Enhance the versioning and release changelog process by integrating it with the conventional commit messages. Automatically generate release notes and changelogs based on the commits made using the conventional commit format. This will provide a clear overview of the changes included in each release.~ **CREATE SEPARATE ISSUES: ONE FOR AUTOMATIC VERSIONING, ONE FOR AUTOMATIC CHANGELOG CREATION**

Once completed, the commit message template enforcement process will be fully implemented and documented in our project's documentation.

**Acknowledgement**

> We thank you for your valuable contribution and would like to acknowledge it
> on our [contributors][contributors] page. To help us with that, we would like
> to kindly request that you help us with this by commenting on this issue with
> a request to the [@all-contributors bot][all-contributors-bot] of the form
> `@all-contributors please add @YOUR_GH_HANDLE for TYPE_1, TYPE_2, ...`, where
> `TYPE_1` etc. refer to [contribution types supported by the All Contributors
> Specification][all-contributors-types].

[all-contributors-bot]: <https://allcontributors.org/docs/en/bot/overview>
[all-contributors-types]: <https://allcontributors.org/docs/en/emoji-key>
[contributors]: ../../CONTRIBUTORS

**Comment by git-anurag-hub** [comment]
@uniqueg, please add any other rules that might help!

**Comment by git-anurag-hub** [comment]
Maybe, we can squash all the commits by the title of the first commit of the referenced PR. This will I think solve the issue. @uniqueg

**Comment by git-anurag-hub** [comment]
This is the way too https://github.com/semantic-release/commit-analyzer/issues/65, we can run the ci-cd that does the commit message change for us automatically & we will also make use of the functionality conventional commits provide!

**Comment by uniqueg** [comment]
I don't agre with the position of the maintainer in the thread you linked. I think it's a totally valid strategy to have messy feature branches, then squash merge them to ensure that we will have _one_ clean commit on the default branch (or development branch, depending on the branching model).

It's very difficult, especially for people who are relatively new to Git, to make perfect PRs with a single semantic commit that has everything and doesn't need changes (trivial ones and more tricky ones), so we will rarely have the situation that we could merge just a beatiful single semantic commit. More likely it's a beautiful single commit, followed by half a dozen small fixes that we don't want to have in the commit message.

Anyway, I didn't fully understand what exactly your/their suggestion is. What we need, basically, is a way to check only the first commit, and then enforce using the first commit as the PR title _and_ commit message for squash merging, as you suggest.

**Comment by uniqueg** [comment]
I think this should do the trick: https://github.com/amannn/action-semantic-pull-request

**Comment by uniqueg** [comment]
Also note that the issue title and discussion are focusing only on _one_ of the aspects in the list. I think we should have individual issues for each of the other points (and for some, possibly even more than one).

**Comment by uniqueg** [comment]
And maybe we should start our CI pipeline with only the semantic pull request action. That seems to me like a reasonable first thing to have in the CI :)

**Comment by git-anurag-hub** [comment]
Yup that action is what I was talking about! @uniqueg 
Yup, I agree with the lifecycle!

**Comment by uniqueg** [comment]
Once again: THIS issue should ONLY focus on enforcing semantic PR messages via GitHub Actions.
There are other useful things listed in the issue description, but these should go into their own issues:
- Automatic versioning
- Automatic changelog updates
- Pre-commit hooks (already exists: #35)

**Comment by uniqueg** [comment]
There are a couple of rules for ~commit messages~ _PR titles_. Only some can be enforced, others have to be described in the [contribution guidelines](https://elixir-cloud-aai.github.io/guides/guide-contributor/workflow/#commit-messages) - where it also has to be made clear that we only require semantic PR titles, _not_ commit messages.

These rules are:
- 50 chars or less
- All lower case except proper nouns
- Use imperative mode (e.g., "add" instead of "adds" or "adding")
- Use bullet point style (skip unnecessary articles etc)
- Okay to use abbreviations like `&`
- Can't use "commit message body", so breaking change needs to be indicated by `!` (see [Conventional Commits spec](https://www.conventionalcommits.org/en/v1.0.0/))
