### ISSUE TITLE
bug: `new` script not working

### ISSUE THREAD

**Issue by ghost** [elixir-cloud-aai/cloud-components#68]
**Describe the bug**
While running `npm run new` script, it is throwing error:
>ERROR Unable to run generate - missing requirements (npx)

**To Reproduce**
> 1. Go to `cloud-components` root folder
> 2. Run `npm run new`

**Expected behavior**
A new package should be created [(see this)](https://github.com/elixir-cloud-aai/cloud-components#:~:text=If%20you%20want%20to%20start%20a%20new%20package%20run%3A)

**Screenshots**
![image](https://github.com/elixir-cloud-aai/cloud-components/assets/95133237/55052bcb-aeec-4a15-a4f4-6280e29ef60e)

**Desktop (please complete the following information):**
Bug is reproducible in Windows OS

**Additional context**
Upgrading the turborepo version to `1.10.2` or more might fix this issue [(see this thread)](https://github.com/vercel/turbo/issues/5075)

**Comment by git-anurag-hub** [comment]
Hey @tanya17-05, can you run `npm i -g npx` once & then try to run the `npm run new` command to see if it works?
